#
# This workflow calls the main distribution pipeline from DuckDB to build, test and (optionally) release the extension
#
name: Main Extension Distribution Pipeline
on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  duckdb-stable-build:
    name: Build extension binaries
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@v1.5.1
    with:
      duckdb_version: v1.5.1
      ci_tools_version: v1.5.1
      extension_name: proto_iceberg
      # iceberg-cpp does not build for Windows or WebAssembly yet.
      exclude_archs: 'windows_amd64;windows_amd64_mingw;wasm_mvp;wasm_eh;wasm_threads'

  code-quality-check:
    name: Code Quality Check
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_code_quality.yml@v1.5.1
    with:
      duckdb_version: v1.5.1
      ci_tools_version: v1.5.1
      extension_name: proto_iceberg
      # FIXME: Disable tidy to prevent full compilation
      format_checks: 'format'
